export const SET_DATA = 'SET_DATA'
export const SET_LOADING = 'SET_LOADING'
export const SET_PHOTO = 'SET_PHOTO'
export const SET_PHOTO_WATCHER = 'SET_PHOTO_WATCHER'
export const SET_ERROR = 'SET_ERROR'
export const TRY_AGAIN = 'TRY_AGAIN'
